name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '7.0.x', '8.0.x' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # - name: Run tests
      #   run: dotnet test --no-build --verbosity normal --configuration Release